@startuml
left to right direction
skinparam DefaultTextAlignment center
skinparam style strictuml
Actor Employee as Emp
usecase "Advise" as UCAdv
usecase "Answer question" as UCAns
usecase "Delete question" as UCDeQ
usecase "Set-up auto Answer " as UCSeAuto
Emp-->UCAdv
(UCAdv)..>(UCAns)
(UCAdv)..>(UCDeQ)
(UCAdv)..>(UCSeAuto)
usecase "Contact" as UCCont
usecase "Receive Requirement" as UCReq /'Tiếp nhận yêu cầu'/
usecase "Export Contact List" as UCExCL /'Xuất danh sách liên hệ'/
Emp-->(UCCont)
(UCCont)..>(UCReq)
(UCCont)..>"<<Extend>>"(UCExCL)
usecase "Login/Logout" as UCAcc
Emp-->"<<include>>"(UCAcc)
'/Đăng tin BDS'/
usecase "Post News" as UCNew
 usecase "Delete News" as UcDeNews
 usecase "Add News" as UcAdNews
 usecase "Edit News" as UcEdNews
 usecase "Set Date"as UCSetDate /'Lên lịch đăng tin'/
 (UCNew)..>"<<include>>"(UCSetDate)
 (UCNew)..>(UcAdNews)
 (UCNew)..>(UcEdNews)
 (UCNew)..>(UcDeNews)
 Emp-->(UCNew)
@enduml